"""Add explanation column to game_predictions

Revision ID: 0cd2bcd0d3a2
Revises: 153dadbd6b03
Create Date: 2026-03-11 22:28:18.763590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd2bcd0d3a2'
down_revision: Union[str, None] = '153dadbd6b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_predictions', sa.Column('explanation', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_predictions', 'explanation')
    # ### end Alembic commands ###
