"""add advanced stats columns to team_season_stats

Revision ID: 28868bb9612c
Revises: 754d313c3ef3
Create Date: 2026-03-10 23:34:25.911761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28868bb9612c'
down_revision: Union[str, None] = '754d313c3ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_season_stats', sa.Column('adj_off_eff', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('adj_def_eff', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('adj_net_eff', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('barthag', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('pyth_win_pct', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('luck', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('true_shooting_pct', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('three_pt_rate', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('ast_to_ratio', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('drb_pct', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('stl_pct', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('blk_pct', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('opp_true_shooting_pct', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('margin_stdev', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('off_eff_stdev', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('floor_eff', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('ceiling_eff', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('upset_vulnerability', sa.Float(), nullable=True))
    op.add_column('team_season_stats', sa.Column('close_wins', sa.Integer(), nullable=True))
    op.add_column('team_season_stats', sa.Column('close_losses', sa.Integer(), nullable=True))
    op.add_column('team_season_stats', sa.Column('close_game_win_pct', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_season_stats', 'close_game_win_pct')
    op.drop_column('team_season_stats', 'close_losses')
    op.drop_column('team_season_stats', 'close_wins')
    op.drop_column('team_season_stats', 'upset_vulnerability')
    op.drop_column('team_season_stats', 'ceiling_eff')
    op.drop_column('team_season_stats', 'floor_eff')
    op.drop_column('team_season_stats', 'off_eff_stdev')
    op.drop_column('team_season_stats', 'margin_stdev')
    op.drop_column('team_season_stats', 'opp_true_shooting_pct')
    op.drop_column('team_season_stats', 'blk_pct')
    op.drop_column('team_season_stats', 'stl_pct')
    op.drop_column('team_season_stats', 'drb_pct')
    op.drop_column('team_season_stats', 'ast_to_ratio')
    op.drop_column('team_season_stats', 'three_pt_rate')
    op.drop_column('team_season_stats', 'true_shooting_pct')
    op.drop_column('team_season_stats', 'luck')
    op.drop_column('team_season_stats', 'pyth_win_pct')
    op.drop_column('team_season_stats', 'barthag')
    op.drop_column('team_season_stats', 'adj_net_eff')
    op.drop_column('team_season_stats', 'adj_def_eff')
    op.drop_column('team_season_stats', 'adj_off_eff')
    # ### end Alembic commands ###
