"""initial schema

Revision ID: 2d8cd60dded7
Revises: 
Create Date: 2026-03-08 14:48:28.979235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8cd60dded7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conferences',
    sa.Column('abbrev', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('abbrev')
    )
    op.create_table('game_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('day_num', sa.Integer(), nullable=False),
    sa.Column('w_team_id', sa.Integer(), nullable=False),
    sa.Column('w_score', sa.Integer(), nullable=False),
    sa.Column('l_team_id', sa.Integer(), nullable=False),
    sa.Column('l_score', sa.Integer(), nullable=False),
    sa.Column('w_loc', sa.String(length=1), nullable=True),
    sa.Column('num_ot', sa.Integer(), nullable=True),
    sa.Column('game_type', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('w_fgm', sa.Integer(), nullable=True),
    sa.Column('w_fga', sa.Integer(), nullable=True),
    sa.Column('w_fgm3', sa.Integer(), nullable=True),
    sa.Column('w_fga3', sa.Integer(), nullable=True),
    sa.Column('w_ftm', sa.Integer(), nullable=True),
    sa.Column('w_fta', sa.Integer(), nullable=True),
    sa.Column('w_or', sa.Integer(), nullable=True),
    sa.Column('w_dr', sa.Integer(), nullable=True),
    sa.Column('w_ast', sa.Integer(), nullable=True),
    sa.Column('w_to', sa.Integer(), nullable=True),
    sa.Column('w_stl', sa.Integer(), nullable=True),
    sa.Column('w_blk', sa.Integer(), nullable=True),
    sa.Column('w_pf', sa.Integer(), nullable=True),
    sa.Column('l_fgm', sa.Integer(), nullable=True),
    sa.Column('l_fga', sa.Integer(), nullable=True),
    sa.Column('l_fgm3', sa.Integer(), nullable=True),
    sa.Column('l_fga3', sa.Integer(), nullable=True),
    sa.Column('l_ftm', sa.Integer(), nullable=True),
    sa.Column('l_fta', sa.Integer(), nullable=True),
    sa.Column('l_or', sa.Integer(), nullable=True),
    sa.Column('l_dr', sa.Integer(), nullable=True),
    sa.Column('l_ast', sa.Integer(), nullable=True),
    sa.Column('l_to', sa.Integer(), nullable=True),
    sa.Column('l_stl', sa.Integer(), nullable=True),
    sa.Column('l_blk', sa.Integer(), nullable=True),
    sa.Column('l_pf', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_game_season', 'game_results', ['season'], unique=False)
    op.create_index('ix_game_season_type', 'game_results', ['season', 'game_type'], unique=False)
    op.create_index('ix_game_teams', 'game_results', ['w_team_id', 'l_team_id'], unique=False)
    op.create_table('model_artifacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('artifact_blob', sa.LargeBinary(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('first_d1_season', sa.Integer(), nullable=True),
    sa.Column('last_d1_season', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conference_strength',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('conf_abbrev', sa.String(length=20), nullable=False),
    sa.Column('avg_elo', sa.Float(), nullable=True),
    sa.Column('elo_depth', sa.Float(), nullable=True),
    sa.Column('top5_elo', sa.Float(), nullable=True),
    sa.Column('nc_winrate', sa.Float(), nullable=True),
    sa.Column('tourney_hist_winrate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['conf_abbrev'], ['conferences.abbrev'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'gender', 'conf_abbrev', name='uq_conf_str')
    )
    op.create_index('ix_conf_str_season_gender', 'conference_strength', ['season', 'gender'], unique=False)
    op.create_table('elo_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('elo', sa.Float(), nullable=False),
    sa.Column('snapshot_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'team_id', 'snapshot_day', name='uq_elo_season_team_day')
    )
    op.create_index('ix_elo_season', 'elo_ratings', ['season'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_b_id', sa.Integer(), nullable=False),
    sa.Column('win_prob_a', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'team_a_id', 'team_b_id', 'model_version', name='uq_pred')
    )
    op.create_index('ix_pred_season_gender', 'predictions', ['season', 'gender'], unique=False)
    op.create_index('ix_pred_team_a', 'predictions', ['team_a_id'], unique=False)
    op.create_index('ix_pred_team_b', 'predictions', ['team_b_id'], unique=False)
    op.create_table('team_conferences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('conf_abbrev', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['conf_abbrev'], ['conferences.abbrev'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'team_id', name='uq_team_conf_season')
    )
    op.create_index('ix_team_conf_season_team', 'team_conferences', ['season', 'team_id'], unique=False)
    op.create_table('team_season_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('win_pct', sa.Float(), nullable=True),
    sa.Column('avg_efg_pct', sa.Float(), nullable=True),
    sa.Column('avg_to_pct', sa.Float(), nullable=True),
    sa.Column('avg_or_pct', sa.Float(), nullable=True),
    sa.Column('avg_ft_rate', sa.Float(), nullable=True),
    sa.Column('avg_opp_efg_pct', sa.Float(), nullable=True),
    sa.Column('avg_opp_to_pct', sa.Float(), nullable=True),
    sa.Column('avg_off_eff', sa.Float(), nullable=True),
    sa.Column('avg_def_eff', sa.Float(), nullable=True),
    sa.Column('avg_tempo', sa.Float(), nullable=True),
    sa.Column('massey_avg_rank', sa.Float(), nullable=True),
    sa.Column('massey_disagreement', sa.Float(), nullable=True),
    sa.Column('last_n_winpct', sa.Float(), nullable=True),
    sa.Column('last_n_mov', sa.Float(), nullable=True),
    sa.Column('efg_trend', sa.Float(), nullable=True),
    sa.Column('conf_tourney_wins', sa.Integer(), nullable=True),
    sa.Column('coach_name', sa.String(length=100), nullable=True),
    sa.Column('coach_tenure', sa.Integer(), nullable=True),
    sa.Column('coach_tourney_appearances', sa.Integer(), nullable=True),
    sa.Column('coach_march_winrate', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'team_id', name='uq_team_stats_season')
    )
    op.create_index('ix_team_stats_season', 'team_season_stats', ['season'], unique=False)
    op.create_table('tourney_seeds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('seed', sa.String(length=4), nullable=False),
    sa.Column('seed_number', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('season', 'team_id', name='uq_seed_season_team')
    )
    op.create_index('ix_seed_season', 'tourney_seeds', ['season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_seed_season', table_name='tourney_seeds')
    op.drop_table('tourney_seeds')
    op.drop_index('ix_team_stats_season', table_name='team_season_stats')
    op.drop_table('team_season_stats')
    op.drop_index('ix_team_conf_season_team', table_name='team_conferences')
    op.drop_table('team_conferences')
    op.drop_index('ix_pred_team_b', table_name='predictions')
    op.drop_index('ix_pred_team_a', table_name='predictions')
    op.drop_index('ix_pred_season_gender', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('ix_elo_season', table_name='elo_ratings')
    op.drop_table('elo_ratings')
    op.drop_index('ix_conf_str_season_gender', table_name='conference_strength')
    op.drop_table('conference_strength')
    op.drop_table('teams')
    op.drop_table('model_artifacts')
    op.drop_index('ix_game_teams', table_name='game_results')
    op.drop_index('ix_game_season_type', table_name='game_results')
    op.drop_index('ix_game_season', table_name='game_results')
    op.drop_table('game_results')
    op.drop_table('conferences')
    # ### end Alembic commands ###
