"""add power_rating to team_season_stats

Revision ID: 7d4d5c9b9d43
Revises: 0cd2bcd0d3a2
Create Date: 2026-03-12 22:46:54.695074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4d5c9b9d43'
down_revision: Union[str, None] = '0cd2bcd0d3a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_season_stats', sa.Column('power_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_season_stats', 'power_rating')
    # ### end Alembic commands ###
