"""add espn_id logo_url color to teams

Revision ID: 904cd28312fd
Revises: 2d8cd60dded7
Create Date: 2026-03-08 15:43:52.203961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '904cd28312fd'
down_revision: Union[str, None] = '2d8cd60dded7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('espn_id', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('teams', sa.Column('color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'color')
    op.drop_column('teams', 'logo_url')
    op.drop_column('teams', 'espn_id')
    # ### end Alembic commands ###
