"""add_sos_to_team_stats

Revision ID: d14585130274
Revises: 904cd28312fd
Create Date: 2026-03-09 16:59:19.640306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14585130274'
down_revision: Union[str, None] = '904cd28312fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_season_stats', sa.Column('sos', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_season_stats', 'sos')
    # ### end Alembic commands ###
